spring:
  servlet:
    multipart:
        enabled: true
        max-file-size: 50MB
        max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/novalib
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      hbm2ddl:
        auto: none
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    add-mappings: true
server:
  port: 8080

upload:
  path: D:/Project/novalib/src/main/resources/static/uploads/
  posterFile:
    path: D:/Project/novalib/src/main/resources/static/uploads/posters/

